################################
# Dune module information file #
################################

# Name of the module
Module: dune-performance-regressions
Version: 0.1
Maintainer: luab00001@stud.uni-saarland.de
# Required build dependencies
Depends: dune-common dune-istl dune-geometry dune-uggrid dune-grid dune-typetree dune-multidomaingrid dune-localfunctions dune-functions dune-pdelab
# Optional build dependencies
#Suggests:
